// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykmuivppswcsnrephrui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrbXVpdnBwc3djc25yZXBocnVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MTQzODQsImV4cCI6MjA2NjE5MDM4NH0.ZOfY5yHZmjGAbJyXMM0IkkAUqDf_hHJT65lSu0_tMu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);